### PR TITLE
bump version to 0.2.1 and update hash

### PR DESCRIPTION
**Pull request by deppen8**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy`
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by deppen8** [comment]
@conda-forge-admin, please rerender

**Comment by deppen8** [comment]
@conda-forge-admin, please rerender

**Comment by deppen8** [comment]
@conda-forge/core Any idea why AppVeyor keeps running and, predictably, failing on my `noarch` package? Seems like the same problem as https://github.com/conda-forge/conda-forge.github.io/issues/736. Should I also re-add through `staged-recipes` as suggested there?

**Comment by isuruf** [comment]
Fixed appveyor settings

**Pull request merged**
